version: '3.3'
services:
  app:
    build:
      context: .
    image: 'store-app'
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    volumes:
      - .:/root/dev/main-project-backend
      - ./.gradle:/root/.gradle

  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=shop'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5455:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
